# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeKAMA <- function(alpha, alphaComplement, KAMA, price) {
    .Call('DSTrading_computeKAMA', PACKAGE = 'DSTrading', alpha, alphaComplement, KAMA, price)
}

computeFRAMA <- function(alpha, alphaComplement, FRAMA, price) {
    .Call('DSTrading_computeFRAMA', PACKAGE = 'DSTrading', alpha, alphaComplement, FRAMA, price)
}

computeItrend <- function(price, iTrend, alpha) {
    .Call('DSTrading_computeItrend', PACKAGE = 'DSTrading', price, iTrend, alpha)
}

computeVIDA <- function(k, price, filt, consts) {
    .Call('DSTrading_computeVIDA', PACKAGE = 'DSTrading', k, price, filt, consts)
}

